# Generated by Django 5.1.4 on 2026-06-03 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=80, unique=True)),
                ('value', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('app_version', models.CharField(default='', max_length=40)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DayClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_date', models.DateField(unique=True)),
                ('total_sales', models.IntegerField(default=0)),
                ('cash_total', models.IntegerField(default=0)),
                ('card_total', models.IntegerField(default=0)),
                ('bank_transfer_total', models.IntegerField(default=0)),
                ('orders_count', models.IntegerField(default=0)),
                ('closed_orders_count', models.IntegerField(default=0)),
                ('open_orders_count', models.IntegerField(default=0)),
                ('table_usage_count', models.IntegerField(default=0)),
                ('purchases_total', models.IntegerField(default=0)),
                ('resource_suggestions_snapshot', models.JSONField(blank=True, default=list)),
                ('sync_status', models.CharField(choices=[('pending', 'در انتظار'), ('synced', 'همگام\u200cشده'), ('failed', 'ناموفق')], default='pending', max_length=16)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-business_date'],
            },
        ),
        migrations.CreateModel(
            name='MenuPublishRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=40)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق')], max_length=16)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.IntegerField(blank=True, null=True)),
                ('updated_by_user_id', models.IntegerField(blank=True, null=True)),
                ('order_number', models.IntegerField(editable=False, unique=True)),
                ('mode', models.CharField(choices=[('table', 'میز'), ('event', 'رویداد')], default='table', max_length=16)),
                ('event_customer_label', models.CharField(blank=True, max_length=160, null=True)),
                ('status', models.CharField(choices=[('open', 'باز'), ('partially_paid', 'پرداخت جزئی'), ('paid', 'پرداخت\u200cشده'), ('closed', 'بسته\u200cشده')], default='open', max_length=20)),
                ('subtotal', models.IntegerField(default=0)),
                ('paid_amount', models.IntegerField(default=0)),
                ('remaining_amount', models.IntegerField(default=0)),
                ('business_date', models.DateField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResourcePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('cost', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('business_date', models.DateField()),
            ],
            options={
                'ordering': ['-business_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResourceSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_name', models.CharField(max_length=160)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('suggested_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_for_date', models.DateField()),
            ],
            options={
                'ordering': ['-created_for_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SyncRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sync_type', models.CharField(choices=[('day_closing', 'بستن روز'), ('menu', 'منو')], max_length=20)),
                ('local_object_id', models.IntegerField(blank=True, null=True)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('synced', 'همگام\u200cشده'), ('failed', 'ناموفق')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.IntegerField(blank=True, null=True)),
                ('updated_by_user_id', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('method', models.CharField(choices=[('cash', 'نقدی'), ('card', 'کارت'), ('bank_transfer', 'کارت\u200cبه\u200cکارت')], max_length=20)),
                ('payer_label', models.CharField(blank=True, max_length=160, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='pos.category')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_user_id', models.IntegerField(blank=True, null=True)),
                ('updated_by_user_id', models.IntegerField(blank=True, null=True)),
                ('product_name_snapshot', models.CharField(max_length=160)),
                ('unit_price_snapshot', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('line_total', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pos.table'),
        ),
    ]
