# Generated by Django 5.1.4 on 2026-06-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_hash_revenue_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='paid_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
