# Generated by Django 5.1.4 on 2026-06-10 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_rename_table_10_saeed_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='day_closing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pos.dayclosing'),
        ),
    ]
