# Generated by Django 5.1.4 on 2026-07-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_rebuild_closings_6am_buckets'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayclosing',
            name='gross_sales',
            field=models.IntegerField(default=0),
        ),
    ]
