# Generated by Django 5.1.4 on 2026-07-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_dayclosing_sync_status_local_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_publishable',
            field=models.BooleanField(default=True),
        ),
    ]
