# Generated by Django 5.1.4 on 2026-07-23 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_order_is_preset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GuestCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('guest_name', models.CharField(blank=True, default='', max_length=160)),
                ('guest_count', models.IntegerField(default=0)),
                ('men_count', models.IntegerField(default=0)),
                ('women_count', models.IntegerField(default=0)),
                ('paid_entry', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='staff_free_monthly_quota',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='staff_free_monthly_quota',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StaffConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_date', models.DateField()),
                ('product_name_snapshot', models.CharField(max_length=160)),
                ('unit_price_snapshot', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('line_total', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='pos.employee')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.product')),
            ],
            options={
                'ordering': ['-business_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', '۹ تا ۱۷'), ('evening', '۱۶ تا ۲۴')], max_length=16)),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
                ('is_full_day', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='pos.employee')),
            ],
            options={
                'ordering': ['-business_date', 'shift', 'id'],
                'unique_together': {('employee', 'business_date', 'shift')},
            },
        ),
    ]
