// Brand generator. Reads the active brand (env BRAND, default "cixis") from
// brands/<id>.json and writes two generated, git-tracked files consumed by the
// app: a CSS file that overrides the theme accent vars, and a TS module that
// exposes the logo glyph / names to React.
//
// Run automatically via the pre* npm hooks (predev, prebuild, pretest,
// preelectron:dev, preelectron:build) — or manually with `npm run gen:brand`.
// For a branded build set BRAND first, e.g. `BRAND=majaz npm run gen:brand`.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

const id = process.env.BRAND || "cixis";
const brandPath = join(root, "brands", `${id}.json`);

let brand;
try {
  brand = JSON.parse(readFileSync(brandPath, "utf8"));
} catch (e) {
  console.error(`[gen-brand] cannot read ${brandPath}: ${e.message}`);
  process.exit(1);
}

const c = brand.colors;
const css = `/* AUTO-GENERATED by scripts/gen-brand.mjs (BRAND=${id}). Do not edit. */
:root {
  --accent: ${c.accent};
  --accent-2: ${c.accent2};
  --brand: ${c.brand};
  --on-accent: ${c.onAccent};
}
`;

const ts = `// AUTO-GENERATED by scripts/gen-brand.mjs (BRAND=${id}). Do not edit.
export const brand = {
  id: ${JSON.stringify(brand.id)},
  productName: ${JSON.stringify(brand.productName)},
  logoGlyph: ${JSON.stringify(brand.logoGlyph)},
  cafeName: ${JSON.stringify(brand.cafeName)},
} as const;
`;

const srcDir = join(root, "src");
mkdirSync(srcDir, { recursive: true });
writeFileSync(join(srcDir, "brand.generated.css"), css);
writeFileSync(join(srcDir, "brand.generated.ts"), ts);

console.log(`[gen-brand] wrote src/brand.generated.{css,ts} for brand "${id}"`);
